GET http://localhost:8000

###
POST http://localhost:8000/broadcast
Content-Type: application/json

{
    "message": "Hello"
}

###
POST https://linebot.osaka.milliax.me/broadcast
Content-Type: application/json

{
    "message": "Hello"
}

###
GET https://linebot.osaka.milliax.me
